name: mpx_app_core
description: "A helper package holding shared classes"
version: 0.0.1
homepage:
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meeting_place_core:
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
      ref: 36221c1aa544555a243c2b4f7a0712969c0ab4e5
      path: packages/meeting_place_core
  meeting_place_credentials:
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
      ref: 36221c1aa544555a243c2b4f7a0712969c0ab4e5
      path: packages/meeting_place_credentials

dev_dependencies:
  dart_flutter_team_lints: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
