name: mpx_app_core
description: "A helper package holding shared classes"
version: 0.0.1
homepage:
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meeting_place_chat: ^0.0.1-dev.0
  meeting_place_core: ^0.0.1-dev.38
  meeting_place_credentials: ^0.0.1-dev.1

dev_dependencies:
  dart_flutter_team_lints: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
