name: meetingplace_flutter_reference_app_workspace
publish_to: "none"

workspace:
  - app
  - packages/app-core

environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  coverage: ^1.11.1
  dart_flutter_team_lints: ^3.2.1
  drift_dev: ^2.28.0
  melos: ^7.1.1

dependency_overrides:
  meeting_place_chat:
    # path: ../affinidi-meetingplace-sdk-dart/packages/meeting_place_chat
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart
      path: packages/meeting_place_chat
      ref: 4d21c4b7b3cddd4ce693bcb9b5f9627d8606c70e
  meeting_place_control_plane:
    # path: ../affinidi-meetingplace-sdk-dart/packages/meeting_place_control_plane
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart
      path: packages/meeting_place_control_plane
      ref: 4d21c4b7b3cddd4ce693bcb9b5f9627d8606c70e
  meeting_place_core:
    # path: ../affinidi-meetingplace-sdk-dart/packages/meeting_place_core
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart
      path: packages/meeting_place_core
      ref: 4d21c4b7b3cddd4ce693bcb9b5f9627d8606c70e
  meeting_place_drift_repository:
    # path: ../affinidi-meetingplace-sdk-dart/packages/meeting_place_drift_repository
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart
      path: packages/meeting_place_drift_repository
      ref: 4d21c4b7b3cddd4ce693bcb9b5f9627d8606c70e
  meeting_place_mediator:
    # path: ../affinidi-meetingplace-sdk-dart/packages/meeting_place_mediator
    git:
      url: https://github.com/affinidi/affinidi-meetingplace-sdk-dart
      path: packages/meeting_place_mediator
      ref: 4d21c4b7b3cddd4ce693bcb9b5f9627d8606c70e

  meta: 1.17.0
  test_api: 0.7.5

melos:
  scripts:
    analyze:
      run: melos run _analyze --no-select
    _analyze:
      exec: dart analyze --fatal-infos .
      concurrency: 4
      failFast: true
      packageFilters:
        scope:
          - mpx_app_core
          - mpx_flutter_reference_app

    test:
      run: |
        melos run test-flutter

    test-flutter:
      description: Run tests in each flutter package
      exec: flutter test --coverage
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: true
        includePrivatePackages: true
        #diff: 'origin/main'
        ignore:
          - "*_example*"

    coverage-html:
      run: dart run melos exec -- "genhtml coverage/lcov.info --output-directory=coverage/html"
      packageFilters:
        scope:
          - mpx_flutter_reference_app
      description: Generate HTML coverage report for app

    pubget:
      run: flutter pub get
      exec:
        concurrency: 5
        orderDependents: true
      description: Get dependencies for all workspace packages

    ios-deps:
      run: |
        melos exec --scope=mpx_flutter_reference_app -- flutter precache --ios
        melos exec --scope=mpx_flutter_reference_app -- "cd ios; pod install --repo-update"

    gen:
      run: |
        echo "------------------------------------------------------------------------"
        echo "Generating code"
        echo "------------------------------------------------------------------------"
        melos exec --scope=mpx_flutter_reference_app -- flutter clean
        melos exec --scope=mpx_flutter_reference_app -- dart run build_runner build --delete-conflicting-outputs
        dart format -l 80 .

    strings:
      run: |
        echo "------------------------------------------------------------------------"
        echo "Generating localized strings"
        echo "------------------------------------------------------------------------"
        melos exec --scope=mpx_flutter_reference_app -- flutter gen-l10n
        dart format -l 80 .
dependencies:
  flutter_vodozemac: ^0.5.0
