name: meeting_place_livekit_flutter
description: Flutter plugin for real-time audio and video call rendering via LiveKit with Matrix RTC integration.
version: 0.0.1-dev.3
repository: https://github.com/affinidi/affinidi-meetingplace-reference-app.git

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_webrtc: ^1.4.0
  livekit_client: ^2.8.1
  matrix: ^8.1.0
  meeting_place_chat: ^0.0.1-dev.56
  meeting_place_core: ^0.0.1-dev.46
  meeting_place_matrix: ^0.0.1-dev.8
  meta: ^1.16.0
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.3
  webrtc_interface: ^1.5.1

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  flutter_test:
    sdk: flutter
